apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-cm
  namespace: gitlab-upgrade
data:
  gitlab.rb: |
    external_url 'https://gitlab-upgrade-new.rancher.pointertech.digital' 
    nginx['listen_port'] = 80
    nginx['listen_https'] = false
    gitlab_rails['gitlab_shell_ssh_port'] = 22
    gitlab_rails['time_zone'] = 'America/Sao_Paulo'
    gitlab_rails['initial_root_password'] = 'NovaSenha'


    # Reduzir uso de recursos
    puma['worker_processes'] = 2
    sidekiq['concurrency'] = 10
    postgresql['shared_buffers'] = "256MB"
    prometheus_monitoring['enable'] = false

    # Desabilitar recursos não essenciais
    gitlab_rails['gitlab_default_projects_features_container_registry'] = false
    gitlab_rails['gitlab_default_projects_features_packages'] = false
    gitlab_rails['gitlab_default_projects_features_pages'] = false

    # Configurações de e-mail (opcional)
    # gitlab_rails['smtp_enable'] = true
    # gitlab_rails['smtp_address'] = "smtp.seu-servidor.com"
    # gitlab_rails['smtp_port'] = 587
    # gitlab_rails['smtp_user_name'] = "seu-usuario"
    # gitlab_rails['smtp_password'] = "sua-senha"
    # gitlab_rails['smtp_domain'] = "seu-dominio.com"
    # gitlab_rails['smtp_authentication'] = "login"
    # gitlab_rails['smtp_enable_starttls_auto'] = true
    # gitlab_rails['gitlab_email_from'] = 'gitlab@seu-dominio.com'
 